##
# TRIONES_HOME
#
# MODULE
# EXTRA_CFLAGS
# EXTRA_INC_PATH
# EXTRA_LIB_PATH
# EXTRA_LIBS
# SRCS
# INCS
# BIN
# SLIB
# DLIB

TRIONES_HOME ?= ${shell readlink -n -e ../.. }

MODULE = net

SLIB = libtrionesnet.a

EXTRA_CFLAGS = -Wno-deprecated 

include ${TRIONES_HOME}/Makefile.inc

